### ISSUE TITLE
Release next version 1.4

### ISSUE THREAD

**Issue by hazendaz** [alextunyk/htmlcompressor-maven-plugin#10]
@alextunyk Can you release 1.4?

**Comment by hazendaz** [comment]
@alextunyk I can make a release provided I get access to sonatype releases for this.  I can raise the ticket.  Not sure how they confirm but wanted to confirm if you are ok with that before I go do it.

**Comment by hazendaz** [comment]
@alextunyk any status on this?  I updated closure compiler now to latest.  And in order to use any of this, it needs to be released.  Htmlcompressor I'm now managing into github for some time.

**Comment by alextunyk** [comment]
Sure, Jeremy.
Could you please also release 1.5-SNAPSHOT and host it at the Sonatype OSS Snapshot as requested by @kevinfaguiar in #11?

**Comment by hazendaz** [comment]
Absolutely I can work on it this weekend.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@alextunyk The groupId is under what appears to be your domain so needed to confirm that was a still active domain otherwise sonatype will kick this back asking that we change group id to github hosting.  So 'com.tunyk.mvn.plugins.htmlcompressor' might need to become 'com.github.alextunyk.maven' or something along those lines.  Before i raise the ticket with them wanted to confirm if you physically own com.tunyk.  If not, if switching to the github hosted version would be sufficent.

**Comment by alextunyk** [comment]
I think it would be just nice to use 'groupId' identifying by the project hosted at github, so something like `io.github.htmlcompressor-maven-plugin.maven` would be perfect.
P.S. The project site is published now at [GitHub Pages](https://alextunyk.github.io/htmlcompressor-maven-plugin/)

**Comment by hazendaz** [comment]
@alextunyk This year has been totally busy and I lost complete track of this.  Hosting is required to be something like 'com.github.alextrunyk' or 'com.github.alextrunyk.maven' where the first 3 portions are hard-requirement of sonatype unless you outright own a domain.  I've been releasing the other portion of htmlcompressor under my account for quite some time and could do the same here since the idea was to change the groupId anyway.  I have a number of maven projects already floating around so I'd go with 'com.github.hazendaz.maven' with everything else the same.  I've also totally revamped this project so it's up-to-date in every way including using latest maven mojo setup via annotations.  I need to push a release of htmlcompressor first before I can jump on that but likely can approach that shortly if no objections.  Then later, what we could do if really wanted is to simply move the entire project plus the underlying htmlcompressor to a github org which would furth remove personal names out of it.  However, that is a bit of work and at the moment I'm not sure to the extent these components are used outside of my own usage on personal and work projects.  Naming aside, everything for now would remain as is.  I'll continue pushing pull requests up through your account as I've been doing and even if we go github org later, I'd continue doing the same as I find it best practice to stay off the direct repo where possible.

**Comment by hazendaz** [comment]
Version 1.4.0 has been released and will be in central within 2 hours.  Closing this task.
