### ISSUE TITLE
Nullpointer in HtmlCompressorMojo

### ISSUE THREAD

**Issue by lindquistfan** [alextunyk/htmlcompressor-maven-plugin#6]
Any plans to fix the TODO on line 441 in HtmlCompressorMojo.java?

**Comment by hazendaz** [comment]
Not seeing the issue.  This is a very old issue request so closing for now.

**Comment by AaronFoltz** [comment]
@hazendaz Still receiving this, and haven't found a way around it.

**Comment by hazendaz** [comment]
This was eventually fixed here https://github.com/alextunyk/htmlcompressor-maven-plugin/commit/8c94225c75f1b20b9f68805e320be48acb02e64e
